### ISSUE TITLE
Dev content review 1

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/guide-graphql-client#2]
- **What you’ll learn**
  - [x] Remove "You will learn how to create a GraphQL client microservice."
  - [x] "...see our GraphQL intro guide." -> "... see the Optimizing REST queries for microservices with GraphQL guide."
  	- [x] the guide link does not work
  - [x] "SmallRye GraphQL client " link should be	https://github.com/smallrye/smallrye-graphql#client
  - [x] should be consistent to use microservice or service instead of using application, microservice, and service
  - "SmallRye GraphQL client supports two types of clients: " paragraph
    - [x] remove the link to the client, unless a doc to talk about typesafe and dynamic
    - [x] I think no need to backtick typesafe, dynamic, and typesafe client
    - [x] May remove "You will implement a typesafe client microservice.". Instead, move this paragraph to the "Implementing a GraphQL client" section

- **Implementing a GraphQL client**
  - [x] reorder as
    - Create the GraphQlClient interface.
    - Create the ClientResource class.
    - Replace the Maven project file.
    - Replace the server configuration file.
  - structure for the above create/replace
    - a brief description of the purpise
    - create/replace instruction
    - detail explain the important code/changes 
  - [x] does `system` mean `SystemInfo`?
  - [x] `query` should not backtick

- **Building and running the application**
  - [x] " The mvn package command packages the system and graphql services." should be client service too

- **Accessing the application**
  - [x] "Try the Retrieve operations" -> "Try the query operations" because no retrieve operation before but query operation
  - [x] "Try the Create operation" -> "Try the mutation operation" same reason

**Comment by priyyanshi** [comment]
Addressing in #3.
