### ISSUE TITLE
Laura's review

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/guide-graphql-client#27]
Generally looks good, I think.

Some minor style/wording suggestions:

* Link “GraphQL concepts” (in first para) to the GraphQL intro doc https://openliberty.io/docs/latest/microprofile-graphql.html (We need to link the guides to the docs more in general, rather than the guides existing independently - the docs can provide more detail than the guides can.)

* “Unlike REST APIs, each request sent to a GraphQL service goes to a single HTTP endpoint.” - I’m not sure how to read this. Doesn’t each REST request go to a single HTTP endpoint too, it’s just that you have to send multiple REST requests? Whereas with GraphQL, you only have to send a single request to the GraphQL service (at a single HTTP endpoint). Isn’t it the sending of the request that matters, rather than the endpoint? (I know this sentence is taken from the other GraphQL guide or the GraphQL doc topic but in both those places there’s more context given.)

* “If the @Mutation annotation was not placed on the function, it would be treated as if it mapped to a query operation.” - should be “If the @Mutation annotation were not placed on the function, it would…” (not “was not”) because it’s talking about a conditional in an alternative reality.

* “In a real application, you make requests to an external GraphQL API,” - should this be “In a real application, you would make requests to an external GraphQL API,”? (Basically saying, this isn’t a real application but in a real application you’d do something differently.)

* In fact, should that be “In a real application, you would make requests to an external GraphQL API, and you might do further manipulation of the data after retrieval.” - that reads better to me I think - is that still accurate?

* “Use the TypesafeGraphQLClientBuilder class to create a client object that implements the GraphQlClient interface and can interact with the graphql microservice. ” - should this be “The TypesafeGraphQLClientBuilder class creates a client object that implements the GraphQlClient interface and can interact with the graphql microservice. ”? Starting with “Use…” reads like it’s an instruction when I think we’re still just describing what the code does here?

* “When the hostname is specified to system-java8, but you can try out the operations using the hostname system-java11 as well. ” - I don’t think this sentence makes sense.

* “When the hostnames are specified to system-java8,system-java11.” Similarly, I don’t think this one makes sense either.

* “You will recieve a 200 response code” - typo “receive”

* “with hostname specified to system-java8.” (And similar other instances) should be “specified as” rather than “specified to”?

**Comment by shin19991207** [comment]
Hi @lauracowen,

> “Unlike REST APIs, each request sent to a GraphQL service goes to a single HTTP endpoint.” - I’m not sure how to read this. Doesn’t each REST request go to a single HTTP endpoint too, it’s just that you have to send multiple REST requests? Whereas with GraphQL, you only have to send a single request to the GraphQL service (at a single HTTP endpoint). Isn’t it the sending of the request that matters, rather than the endpoint? (I know this sentence is taken from the other GraphQL guide or the GraphQL doc topic but in both those places there’s more context given.)

"GraphQL is an open source data query language. You can use a GraphQL service to obtain data from multiple sources, such as APIs, databases, and other services. GraphQL services require less data fetching than REST services, which results in faster application load times and lower data transfer costs." - is this better?

> “In a real application, you make requests to an external GraphQL API,” - should this be “In a real application, you would make requests to an external GraphQL API,”? (Basically saying, this isn’t a real application but in a real application you’d do something differently.)
> In fact, should that be “In a real application, you would make requests to an external GraphQL API, and you might do further manipulation of the data after retrieval.” - that reads better to me I think - is that still accurate?

Used "In a real application, you would make requests to an external GraphQL API, and you might do further manipulation of the data after retrieval." instead, which looks most accurate to me. 

> “Use the TypesafeGraphQLClientBuilder class to create a client object that implements the GraphQlClient interface and can interact with the graphql microservice. ” - should this be “The TypesafeGraphQLClientBuilder class creates a client object that implements the GraphQlClient interface and can interact with the graphql microservice. ”? Starting with “Use…” reads like it’s an instruction when I think we’re still just describing what the code does here?

Correct. Fixed the sentence.

> "When the hostname is specified to system-java8, but you can try out the operations using the hostname system-java11 as well. The response is similar to the following example:" - I don’t think this sentence makes sense.

"The response is similar to the following example when the `hostname` is specified to `system-java8`, but you can try out the operations using the hostname `system-java11` as well:" - is this better?

> “When the hostnames are specified to system-java8,system-java11.” Similarly, I don’t think this one makes sense either.

"When the `hostnames` are specified to `system-java8,system-java11`, the response is similar to the following example:" - is this better?

> “with hostname specified to system-java8.” (And similar other instances) should be “specified as” rather than “specified to”?

Corrected the wording to “specified as”.

All the other comments for wording were addressed in https://github.com/OpenLiberty/draft-guide-graphql-client/pull/28. You can see the changes at http://lgdev1.fyre.ibm.com:4020/guides/graphql-client.html.

**Comment by yeekangc** [comment]
> “In a real application, you would make requests to an external GraphQL API, and you might do further manipulation of the data after retrieval.”

Should we refer to it as a "service" instead of an "API"?

**Comment by shin19991207** [comment]
Hi @yeekangc,


> > “In a real application, you would make requests to an external GraphQL API, and you might do further manipulation of the data after retrieval.”
> 
> Should we refer to it as a "service" instead of an "API"?

Yes, that would be more accurate. Thanks for the suggestion and I've applied the changes in https://github.com/OpenLiberty/draft-guide-graphql-client/pull/28.

**Comment by gkwan-ibm** [comment]
close
- comments were addressed by the PR #28
