### ISSUE TITLE
Daily build failure

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/guide-graphql-client#36]
need to fix the following
- `scripts/dailyBuild.sh`
   - remove `graphql/pom.xml ` from the first `sed` command 
   - add the following
```
sed -i "\#<looseApplication>false</looseApplication>#a<install><runtimeUrl>https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/runtime/nightly/"$DATE"/"$DRIVER"</runtimeUrl></install>"  graphql/pom.xml
```
  - the second `sed` is not right, it should replace `FROM icr.io/appcafe/open-liberty:full-${JAVA_VERSION}-openj9-ubi`
    - the characters `$`, `{`, and `}` need special handle

**Comment by shin19991207** [comment]
- Addressed in https://github.com/OpenLiberty/guide-graphql-client/pull/38
- Daily build passed at https://github.com/OpenLiberty/guides-common/actions/runs/3061189651

**Comment by gkwan-ibm** [comment]
close
- test passed on today builds
