### ISSUE TITLE
Enable docker daily test

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/guide-graphql-client#37]
- create `dockerImageTest.sh` similar to the [getting started guide dockerImageTest.sh](https://github.com/OpenLiberty/guide-getting-started/blob/prod/scripts/dockerImageTest.sh)
  - `sed` commands should be same as this guide [dailyBuild.sh](https://github.com/OpenLiberty/guide-graphql-client/blob/prod/scripts/dailyBuild.sh)
- add this guide to [docker-guides.json](https://github.com/OpenLiberty/guides-common/blob/prod/.github/workflows/docker-guides.json)

**Comment by shin19991207** [comment]
> create dockerImageTest.sh similar to the [getting started guide dockerImageTest.sh](https://github.com/OpenLiberty/guide-getting-started/blob/prod/scripts/dockerImageTest.sh)

Addressed in https://github.com/OpenLiberty/guide-graphql-client/pull/39

> add this guide to [docker-guides.json](https://github.com/OpenLiberty/guides-common/blob/prod/.github/workflows/docker-guides.json)

Addressed in https://github.com/OpenLiberty/guides-common/pull/843

**Comment by gkwan-ibm** [comment]
close
- test passed on today docker daily test
